# Numerical Python Library: numpy

* numpy is a  multi dimensional array library

In [1]:
import numpy as np

### The basics (creating arrays, shape, size, data,type)

In [2]:
a=np.array([1,2,3]) #one dim array

In [3]:
a

array([1, 2, 3])

In [4]:
b=np.array([ [9,6,3],[5,3,7],[2,15,3] ])
b

array([[ 9,  6,  3],
       [ 5,  3,  7],
       [ 2, 15,  3]])

In [5]:
#Array dimention
a.ndim

1

In [6]:
b.ndim

2

In [7]:
#shape on an array
b.shape

(3, 3)

In [8]:
a.shape

(3,)

In [9]:
c=np.array([ [1,2,3],[4,5,6] ])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
c.shape

(2, 3)

In [11]:
b

array([[ 9,  6,  3],
       [ 5,  3,  7],
       [ 2, 15,  3]])

In [12]:
b[1,0]

5

In [13]:
#you can slice
b[0,:]

array([9, 6, 3])

In [14]:
b[:,2]

array([3, 7, 3])

### Initializing different types of arrays

In [15]:
#np.zeros((shape))
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
#np.ones((shape))
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
#np.full((shape),value)
np.full((3,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [18]:
#Random decimal numbers
np.random.rand(3,2)

array([[0.54556977, 0.46866269],
       [0.42731894, 0.90195009],
       [0.72898227, 0.55263752]])

In [19]:
#Random Integer Values  np.random.randint(Min,Max,(shape))
np.random.randint(0,5,(4,3))

array([[1, 1, 4],
       [2, 1, 3],
       [3, 1, 4],
       [4, 1, 3]])

In [20]:
#Identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Copying arrays!

* b=a => b point vers a
* b=a.copy() => make a copy

In [21]:
e=b.copy()
e

array([[ 9,  6,  3],
       [ 5,  3,  7],
       [ 2, 15,  3]])

### Mathematics

In [22]:
a=np.array([3,4,2])

In [23]:
a+2

array([5, 6, 4])

In [24]:
a

array([3, 4, 2])

In [25]:
a-2

array([1, 2, 0])

In [26]:
a*2

array([6, 8, 4])

In [27]:
a/2

array([1.5, 2. , 1. ])

In [28]:
b=np.array([4,6,9])

In [29]:
b

array([4, 6, 9])

In [30]:
a

array([3, 4, 2])

In [31]:
a+b

array([ 7, 10, 11])

In [32]:
a**2

array([ 9, 16,  4])

In [33]:
np.sin(a)

array([ 0.14112001, -0.7568025 ,  0.90929743])

In [34]:
np.cos(a)

array([-0.9899925 , -0.65364362, -0.41614684])

In [35]:
#check doc for more useful functions

### Liniar Algebra

In [36]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
b=np.full((3,2),4)
b

array([[4, 4],
       [4, 4],
       [4, 4]])

In [38]:
#a*b like in algebra
np.matmul(a,b)

array([[12., 12.],
       [12., 12.]])

In [39]:
#check docs for more

### Stats

In [40]:
a=np.array([[3,4,1,8],
           [5,9,3,4]])
a

array([[3, 4, 1, 8],
       [5, 9, 3, 4]])

In [41]:
np.min(a)

1

In [42]:
np.max(a)

9

In [43]:
np.sum(a)

37

In [44]:
np.max(a,axis=0)

array([5, 9, 3, 8])

In [45]:
np.max(a,axis =1)

array([8, 9])